use_frameworks!

target 'FactoryCustomImageWithButton_Example' do
  pod 'FactoryCustomImageWithButton', :path => '/Users/matejhetzel/Desktop/untitled folder 2/FactoryCustomImageWithButton'

  target 'FactoryCustomImageWithButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
